name: Teams
version: '0.0.2'
main: org.khenas.teams.Teams
api-version: '1.21'
commands:
  create:
    description: "Create a team, the leader will be the command sender."
    usage: "/create [teamname]"
    permission: teams.command.create
    permission-message: "You do not have permission to use this command."
  list:
    description: "Show all the team in a list format."
    usage:  "/list"
    permission: teams.command.list
    permission-message: "You do not have permission to use this command."
  myteam:
    description: "Show the team of the invocator's command"
    usager: "/myteam"
    permission: teams.command.myteam
    permission-message: "You do not have permission to use this command."
