name: Teams
version: '0.0.3'
main: org.khenas.teams.Teams
api-version: '1.21'
commands:
  tcreate:
    description: "Create a team, the leader will be the command sender."
    usage: "/tcreate [teamname]"
    permission: teams.command.create
    permission-message: "You do not have permission to use this command."
  tlist:
    description: "Show all the team in a list format."
    usage:  "/tlist"
    permission: teams.command.list
    permission-message: "You do not have permission to use this command."
  tmyteam:
    description: "Show the team of the invocator's command"
    usage: "/tmyteam"
    permission: teams.command.myteam
    permission-message: "You do not have permission to use this command."
